apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: couchbaseclusters.couchbase.com
spec:
  group: couchbase.com
  names:
    kind: CouchbaseCluster
    listKind: CouchbaseClusterList
    plural: couchbaseclusters
    singular: couchbasecluster
    shortNames:
    - cbc
  scope: Namespaced
  versions:
  - name: v2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}

