apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: couchbase
spec:
  global:
    site: datadoghq.com
    kubelet:
      tlsVerify: false
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
    clusterName: minikube-couchbase
  features:
    apm:
      enabled: true
      instrumentation:
        enabled: true
    logCollection:
      enabled: true
      containerCollectAll: true
    orchestratorExplorer:
      enabled: true
  override:
    nodeAgent:
      env:
        - name: DD_LOGS_CONFIG_AUTO_MULTI_LINE_DETECTION
          value: "true"
        - name: DD_INTEGRATIONS_ENABLED
          value: "couchbase"
        - name: DD_COUCHBASE_ENABLED
          value: "true"
      containers:
        agent:
          env:
            - name: DD_AUTODISCOVERY_ENABLED
              value: "true"

